name: Build, push and deploy docker image
on:
  push:

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build --build-arg BACKEND_API_URL = ${{ secrets.BACKEND_API_URL}} -t vincentramaputra/viscord-web:latest .
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
      - name: push image to docker hub
        run: |
          docker push vincentramaputra/viscord-web:latest
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: vincent
          password: ${{ secrets.AZURE_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /app/viscord
            sudo docker compose pull
            sudo docker compose up -d
